# Comparison of data pipelines

## Import modules

In [ ]:
import pandas as pd

## Data ingestion

We need to develop a single method for data ingestion for the data pipeline. Currently we have two.

In [31]:
df = pd.read_csv("vodafone_reviews.csv")
df.head(2)

,review_id,title,review,score,timestamp
0,1,Vodaphone Almost Ruined My Life - Stolen Ident...,My email and password were part of a company d...,1,2021-01-31 01:03:34+00:00
1,2,Misguided Sale,"Misguided SaleCouple of days ago, I was told t...",1,2021-01-29 08:59:16+00:00

### Nikki code

In [32]:
import pandas as pd
text_df = pd.read_pickle("NF_text_feature_df")
text_df.head(3)

,line_num,review_id,score,timestamp,nps_category,nps_class,text,sentences,sentence,clean_text,...,NEs,NE_labels,noun_strings,lemmatised_phrases_no_sw,lemmatised_bigrams,lemmatised_trigrams,lemmatised_bigrams_no_sw,lemmatised_trigrams_no_sw,lemmatised_bigrams_no_sw_alt,lemmatised_trigrams_no_sw_alt
0,0,1,1,2021-01-31 01:03:34+00:00,Detractor,-1,Vodaphone Almost Ruined My Life - Stolen Ident...,[Vodaphone Almost Ruined My Life - Stolen Iden...,Vodaphone Almost Ruined My Life - Stolen Ident...,Vodaphone Almost Ruined My Life - Stolen Ident...,...,[Vodaphone Almost],[PERSON],vodaphone my_life_-_stolen_identity_-_zero_sec...,"[vodaphone, my_life_-_stolen_identity_-_zero_s...","[(vodaphone, almost), (almost, ruin), (ruin, m...","[(vodaphone, almost, ruin), (almost, ruin, my)...","[(life, stolen), (stolen, identity), (identity...","[(life, stolen, identity), (stolen, identity, ...","[(vodaphone, ruin), (ruin, life), (life, stole...","[(vodaphone, ruin, life), (ruin, life, stolen)..."
1,0,1,1,2021-01-31 01:03:34+00:00,Detractor,-1,Vodaphone Almost Ruined My Life - Stolen Ident...,[Vodaphone Almost Ruined My Life - Stolen Iden...,My email and password were part of a company ...,My email and password were part of a company d...,...,"[a few months ago, Vodaphone]","[DATE, GPE]",my_email password part a_company_database hack...,"[my_email, password, a_company_database, hacke...","[(my, email), (email, and), (and, password), (...","[(my, email, and), (email, and, password), (an...","[(company, database), (database, leak), (month...","[(company, database, leak)]","[(email, password), (password, company), (comp...","[(email, password, company), (password, compan..."
2,0,1,1,2021-01-31 01:03:34+00:00,Detractor,-1,Vodaphone Almost Ruined My Life - Stolen Ident...,[Vodaphone Almost Ruined My Life - Stolen Iden...,"(Vodaphone has 0 security in place, they don'...","(Vodaphone has zero security in place, they do...",...,"[Vodaphone, zero, twoFA, Two]","[ORG, CARDINAL, DATE, CARDINAL]",vodaphone zero_security place they twofa (two_...,"[vodaphone, zero_security, place, twofa, two_f...","[(vodaphone, have), (have, zero), (zero, secur...","[(vodaphone, have, zero), (have, zero, securit...","[(zero, security), (offer, twofa), (factor, au...",[],"[(vodaphone, zero), (zero, security), (securit...","[(vodaphone, zero, security), (zero, security,..."

In [33]:
sentence_df = pd.read_pickle("NF_sentence_feature_df")
sentence_df.head(3)

,line_num,review_id,score,timestamp,nps_category,nps_class,text,sentences,sentence,clean_text,...,NEs,NE_labels,noun_strings,lemmatised_phrases_no_sw,lemmatised_bigrams,lemmatised_trigrams,lemmatised_bigrams_no_sw,lemmatised_trigrams_no_sw,lemmatised_bigrams_no_sw_alt,lemmatised_trigrams_no_sw_alt
0,0,1,1,2021-01-31 01:03:34+00:00,Detractor,-1,Vodaphone Almost Ruined My Life - Stolen Ident...,[Vodaphone Almost Ruined My Life - Stolen Iden...,Vodaphone Almost Ruined My Life - Stolen Ident...,Vodaphone Almost Ruined My Life - Stolen Ident...,...,[Vodaphone Almost],[PERSON],vodaphone my_life_-_stolen_identity_-_zero_sec...,"[vodaphone, my_life_-_stolen_identity_-_zero_s...","[(vodaphone, almost), (almost, ruin), (ruin, m...","[(vodaphone, almost, ruin), (almost, ruin, my)...","[(life, stolen), (stolen, identity), (identity...","[(life, stolen, identity), (stolen, identity, ...","[(vodaphone, ruin), (ruin, life), (life, stole...","[(vodaphone, ruin, life), (ruin, life, stolen)..."
1,0,1,1,2021-01-31 01:03:34+00:00,Detractor,-1,Vodaphone Almost Ruined My Life - Stolen Ident...,[Vodaphone Almost Ruined My Life - Stolen Iden...,My email and password were part of a company ...,My email and password were part of a company d...,...,"[a few months ago, Vodaphone]","[DATE, GPE]",my_email password part a_company_database hack...,"[my_email, password, a_company_database, hacke...","[(my, email), (email, and), (and, password), (...","[(my, email, and), (email, and, password), (an...","[(company, database), (database, leak), (month...","[(company, database, leak)]","[(email, password), (password, company), (comp...","[(email, password, company), (password, compan..."
2,0,1,1,2021-01-31 01:03:34+00:00,Detractor,-1,Vodaphone Almost Ruined My Life - Stolen Ident...,[Vodaphone Almost Ruined My Life - Stolen Iden...,"(Vodaphone has 0 security in place, they don'...","(Vodaphone has zero security in place, they do...",...,"[Vodaphone, zero, twoFA, Two]","[ORG, CARDINAL, DATE, CARDINAL]",vodaphone zero_security place they twofa (two_...,"[vodaphone, zero_security, place, twofa, two_f...","[(vodaphone, have), (have, zero), (zero, secur...","[(vodaphone, have, zero), (have, zero, securit...","[(zero, security), (offer, twofa), (factor, au...",[],"[(vodaphone, zero), (zero, security), (securit...","[(vodaphone, zero, security), (zero, security,..."

### Matt Code

In [28]:
from data_loader import load_path
data_path = 'pre_processed_vodafone_data.csv'

df = load_path(data_path)
df.head(2)

,review_id,title,review,score,timestamp,review_sentiment,sentences,lemmatised_title,noun_phrases,lemmatised_sentences,bi_grams,tri_grams,words,nouns
0,1,vodafone almost ruined my life - stolen identi...,my email and password were part of a company d...,1,2021-01-31 01:03:34+00:00,-0.9390,[(vodafone almost ruined my life - stolen iden...,vodafone almost ruin life steal identity security,"[(company database leak, -0.34, 1), (vodafone ...",[(vodafone almost ruin life steal identity sec...,"[(ruin life, -0.5584, 1), (life steal, -0.5584...","[(vodafone almost ruin, -0.5584, 1), (ruin lif...","[(vodafone, -0.5584, 1), (almost, -0.5584, 1),...","[(vodafone, -0.5584, 1), (life, -0.5584, 1), (..."
1,2,misguided sale,"misguided salecouple of days ago, i was told t...",1,2021-01-29 08:59:16+00:00,0.8555,"[(misguided sale, 0.0, 1), (misguided salecoup...",misguide sale,"[(trade in value, 0.34, 1), (old phone, 0.34, ...","[(misguide, 0.0, 1), (misguided salecouple day...","[(misguide sale, 0.0, 1), (misguided salecoupl...","[(misguided salecouple day, 0.34, 1), (trade i...","[(misguide, 0.0, 1), (misguided, 0.34, 1), (sa...","[(misguide, 0.0, 1), (salecouple, 0.34, 1), (d..."